SELECT *
FROM department;

SELECT DEPTNO, DEPTNAME
FROM department;

SELECT TITLE
FROM employee;

SELECT DISTINCT TITLE
FROM employee;

SELECT *
FROM employee
WHERE DNO = 2;

SELECT EMPNAME, TITLE, DNO
FROM employee
WHERE empname LIKE '이%';

SELECT FLOOR 
FROM department
WHERE DEPTNAME = '영업' OR DEPTNAME = '개발';

SELECT EMPNAME, SALARY
FROM employee
WHERE title = '과장' AND DNO = 1;

SELECT EMPNAME, SALARY
FROM employee
WHERE TITLE = '과장' AND DNO <> 1;

SELECT EMPNAME, TITLE, SALARY
FROM employee
WHERE salary BETWEEN 3000000 AND 4500000;

SELECT *
FROM employee
WHERE dno IN (1,3);

SELECT EMPNAME, SALARY, SALARY * 1.1 AS NEWSALARY
FROM employee
WHERE title = '과장';

SELECT EMPNO, EMPNAME
FROM employee
WHERE DNO IS NULL;

SELECT SALARY, TITLE, EMPNAME
FROM employee
WHERE DNO = 2
ORDER BY salary;

SELECT AVG(SALARY) AS AVGSAL, MAX(SALARY) AS MAXSAL
FROM employee;

SELECT DNO, AVG(SALARY) AS AVGSAL, MAX(SALARY) AS MAXSAL
FROM employee
GROUP BY DNO;

SELECT DNO, AVG(SALARY) AS AVGSAL, MAX(SALARY) AS MAXSAL
FROM employee
GROUP BY DNO
HAVING AVG(salary) >= 2500000;

(SELECT DNO
FROM employee
WHERE EMPNAME = '김창섭')
UNION
(SELECT DEPTNO
FROM department
WHERE DEPTNAME = '개발');

SELECT EMPNAME, DEPTNAME
FROM department D, employee E
WHERE E.DNO = D.DEPTNO;

SELECT E.EMPNAME, M.EMPNAME
FROM employee E, employee M
WHERE E.MANAGER = M.EMPNO;

SELECT DEPTNAME, EMPNAME, TITLE, SALARY
FROM employee E, department D
WHERE E.DNO = d.deptno
ORDER BY DEPTNAME, SALARY DESC;

SELECT EMPNAME, TITLE 
FROM employee
WHERE TITLE = 
    (SELECT TITLE
    FROM employee
    WHERE EMPNAME = '박영권');
    
SELECT EMPNAME
FROM employee E, department D
WHERE E.DNO = D.deptno
    AND (D.DEPTNAME = '영업' OR D.DEPTNAME = '개발'); 
